#!/usr/bin/env bash
# runai client uninstall — reverses everything `runai-client-install.sh`
# did: removes the UserPromptSubmit hook entry pointing at ~/.runai-hook.sh
# from ~/.claude/settings.json, drops the runai-client remote MCP entry from
# ~/.claude.json's mcpServers, deletes the hook script itself, and removes
# the installer-generated server fingerprint pin.
#
# Usage:
#   curl -fsSL http://<SERVER>:<PORT>/uninstall | bash
#
# Safe to run if you never installed — both steps are no-ops in that case.

set -euo pipefail

HOOK_PATH="$HOME/.runai-hook.sh"
SERVER_PIN_PATH="$HOME/.runai-server.json"
SETTINGS_PATH="$HOME/.claude/settings.json"
CLAUDE_JSON_PATH="$HOME/.claude.json"

echo "runai client uninstall"
echo

is_safe_skill_name() {
  case "${1:-}" in
    ""|"."|".."|*/*|*\\*|*[!A-Za-z0-9_-]*)
      return 1
      ;;
    *)
      return 0
      ;;
  esac
}

target_dir_for() {
  case "$1" in
    claude|codex|gemini|opencode)
      printf '%s' "$HOME/.$1/skills"
      ;;
    *)
      return 1
      ;;
  esac
}

# 1) Remove the hook entry from settings.json (if present). Idempotent.
if [[ -f "$SETTINGS_PATH" ]]; then
  cp "$SETTINGS_PATH" "${SETTINGS_PATH}.runai-uninstall-bak"
  python3 - "$SETTINGS_PATH" "$HOOK_PATH" <<'PY'
import json
import sys

settings_path = sys.argv[1]
hook_path = sys.argv[2]

with open(settings_path) as f:
    try:
        data = json.load(f)
    except json.JSONDecodeError:
        print('settings.json was not valid JSON — leaving untouched')
        sys.exit(0)

hooks = data.get('hooks', {})
ups = hooks.get('UserPromptSubmit', [])

removed = 0
new_ups = []
for group in ups:
    inner = group.get('hooks', [])
    kept = [h for h in inner if h.get('command') != hook_path]
    if not kept:
        # whole group was ours — drop the wrapper too
        removed += len(inner)
        continue
    if len(kept) != len(inner):
        removed += len(inner) - len(kept)
    new_ups.append({**group, 'hooks': kept})

if new_ups:
    hooks['UserPromptSubmit'] = new_ups
elif 'UserPromptSubmit' in hooks:
    del hooks['UserPromptSubmit']

with open(settings_path, 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')

print(f'removed {removed} runai hook entr{"y" if removed == 1 else "ies"} from settings.json')
PY
else
  echo "no settings.json — nothing to clean"
fi

# 2) Remove the runai-client remote MCP entry from ~/.claude.json (§1.6 mcp
#    leg). Only the `runai-client` key under mcpServers is dropped; every
#    other mcpServers entry and top-level key is preserved. Idempotent —
#    no-op when the entry / file is absent.
if [[ -f "$CLAUDE_JSON_PATH" ]]; then
  cp "$CLAUDE_JSON_PATH" "${CLAUDE_JSON_PATH}.runai-uninstall-bak"
  python3 - "$CLAUDE_JSON_PATH" <<'PY'
import json
import sys

claude_path = sys.argv[1]
try:
    with open(claude_path) as f:
        data = json.load(f)
except (FileNotFoundError, json.JSONDecodeError):
    print("claude.json not valid JSON — leaving untouched")
    sys.exit(0)

servers = data.get("mcpServers")
if isinstance(servers, dict) and "runai-client" in servers:
    del servers["runai-client"]
    with open(claude_path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print("removed runai-client remote MCP from claude.json")
else:
    print("no runai-client remote MCP entry — nothing to clean")
PY
else
  echo "no $CLAUDE_JSON_PATH — nothing to clean"
fi

# 3) Delete the hook wrapper script itself.
if [[ -f "$HOOK_PATH" ]]; then
  rm -f "$HOOK_PATH"
  echo "removed $HOOK_PATH"
else
  echo "no $HOOK_PATH — already clean"
fi

# 4) Remove the server fingerprint pin generated by install. This is not a
#    user auth token; it is trust state owned by the remote-client install.
if [[ -f "$SERVER_PIN_PATH" ]]; then
  rm -f "$SERVER_PIN_PATH"
  echo "removed $SERVER_PIN_PATH"
else
  echo "no $SERVER_PIN_PATH — already clean"
fi

# 5) Remove skills that `runai-client get` materialised into local CLI agent
#    dirs, tracked in ~/.runai-local-skills (one "<target>\t<name>" per line).
#    Only dirs we recorded are removed; everything else is left untouched.
LOCAL_MANIFEST="$HOME/.runai-local-skills"
if [[ -f "$LOCAL_MANIFEST" ]]; then
  removed_local=0
  while IFS=$'\t' read -r t name; do
    [[ -n "$t" && -n "$name" ]] || continue
    if ! is_safe_skill_name "$name"; then
      echo "skipped unsafe manifest entry: $t / $name"
      continue
    fi
    target_dir="$(target_dir_for "$t" || true)"
    [[ -n "$target_dir" ]] || continue
    d="$target_dir/$name"
    if [[ -d "$d" ]]; then
      rm -rf "$d"
      removed_local=$((removed_local + 1))
    fi
  done < "$LOCAL_MANIFEST"
  rm -f "$LOCAL_MANIFEST"
  echo "removed $removed_local locally-installed skill(s) + $LOCAL_MANIFEST"
else
  echo "no locally-installed skills tracked — nothing to clean"
fi

# 6) Remove the runai-client companion command itself.
CLIENT_BIN="$HOME/.local/bin/runai-client"
if [[ -f "$CLIENT_BIN" ]]; then
  rm -f "$CLIENT_BIN"
  echo "removed $CLIENT_BIN"
fi

echo
echo "done. Claude Code will no longer call runai on UserPromptSubmit."
echo "your original settings.json was backed up to ${SETTINGS_PATH}.runai-uninstall-bak"
